services:
  - type: web
    name: volleyball-app-backend
    runtime: node
    region: frankfurt # You can change this to your preferred region
    buildCommand: "./server/render-build.sh"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 # Stable LTS version compatible with your dependencies
      - key: NODE_ENV
        value: development
      - key: MONGO_URI
        sync: false # You'll need to set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
      - key: PORT
        value: 5000 # Render's default port
      - key: CORS_ORIGIN
        sync: false # Set this to your frontend URL in Render dashboard
    healthCheckPath: /api/health # You may need to add this endpoint
    autoDeploy: false # Set to true if you want automatic deploys from GitHub

    
  # Frontend Static Site
  - type: static
    name: volleyball-app-frontend
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: ./client/build
    headers:
      # HTML files should not be cached
      - path: /
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate, max-age=0
      # Add ETag support
      - path: /*
        name: ETag
        value: "v1.0"  
      # Service worker should not be cached
      - path: /service-worker.js
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      # Static assets can be cached
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
      # Security headers
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: REACT_APP_API_URL
        sync: false # Set in Render dashboard
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true # Enable if you want automatic deploys from GitHub