services:
  # Backend Service
  - type: web
    name: volleyball-app-backend
    runtime: node
    region: frankfurt
    buildCommand: "./server/render-build.sh"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: false

  # Frontend Static Site - FIXED CONFIGURATION
  - type: static
    name: volleyball-app-frontend
    buildCommand: "cd client && npm ci && npm run build && cp public/_redirects build/_redirects"
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /service-worker.js
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    autoDeploy: true